### PR TITLE
First pull request to translate learn-nodejs-hard-way repository into Brazilian Portuguese.

### PR DESCRIPTION
**Pull request by lucaspicinini**
## Information about the first pull request and some considerations about adjusting my workflow.

Due to my little experience, two of the commits (`b40b625` and `53e21f0`) were made with more than 1 file, but I believe you will be able to understand, as I will make some clarifications below to make it easier. I made the pull request with what I already have, but from now on, I will keep one file per commit as you indicated and try to commit only with the completed file; and only then make a new pull request. I believe this way it will be more organized for you. If you have any other preferences or tips for the workflow, just let me know here.

### About the translation. Briefly:

- ./chapters/* (100%)
- ./code/* (100%)
- ./CODE_OF_CONDUCT.md (100%)
- ./CONTRIBUTING.md (100%)
- ./SECURITY.md (100%)
- ./Readme.md (100%)

So far, in this first pull request, these were the files changed. I haven't changed any file names too, I thought it would be better to leave this work to be done at the end, that way the link structure wouldn't be affected during translation. Only raw text was translated and some things like strings in examples or variable names in examples, to make the material as pt-br native as possible, but the logic of the code, the meaning of the example or your way of teaching was not affected.

### CODE REVIEW

**Review by ishtms — CHANGES_REQUESTED** [review]
@lucaspicinini Everything is fine, but the variable names, file names etc should not be translated.

**Comment by lucaspicinini** [comment]
Hey @ishtms , no problem my friend... I'm working on chapter 5.1 now, as soon as I finish it, I'll correct the names of variables, files, etc... But I still have a question... About the strings in the examples ... I'm not talking about Logtar, Velocy, etc... Just examples!!! Don't you think they should be translated? I believe it would be better for teaching purposes, but I will wait for your opinion, as I am learning a lot from your experience... As soon as you let me know your preference here, I will edit previous files... Another thing. As I'm doing a native translation, line by line, I ended up noticing small things that would be interesting to improve in the project... They're not exactly errors, but for example, some code snippet outputs are wrapped with ```js, while others with ```bash, and in some cases, they are the same type of output, and other small standardizations of this type that I believe are important to further improve this beautiful book, since I believe that this is just the beginning of a great project (these are things you might have just accidentally done while editing). I am writing down all these POSSIBLE improvements in a file, so that at the end of the translation, I can pass these considerations on to you. I had opened an issue when I found an error in the first file (calculate !== calculator on line 32), but I'm going to delete it and gather all these possible improvements in a final file, as I saw that they will appear during the translation. Just so you know why I'm going to delete this issue... I believe it will be more organized by bringing everything together at the end. Thank you in advance for your patience and help with me, this translation has been a turning point in my learning, I will definitely remember it...

**Comment by lucaspicinini** [comment]
The main work is done buddy. I would like to thank you once again for your work, it has helped me a lot in learning. I will soon make a pull request for the main branch with some small typo corrections that I noted during the translation.

**Comment by lucaspicinini** [comment]
How are you my bro @ishtms? I hope all is well with you... I imagine you are very busy with other projects, but we have any chance of you continuing with this book in 2024? We miss you sharing your knowledge with us. A big hug from Brazil.

**Comment by ishtms** [comment]
Hi @lucaspicinini, thanks for your work. I have been quite busy with some other work.

While I've been considering the translation aspect, it's important to note that this book's content is still in a very early stage, with frequent updates and corrections occurring almost daily. That way it would be impractical to translate each change/update.

I believe a more efficient approach would be to begin the translation process when the project nears completion. This way we would minimize the need for constant revisions to the translated content.

**Comment by lucaspicinini** [comment]
No problem @ishtms , your material has helped me a lot, I still refer to it many times to revisit concepts that you explained very well. I think the approach you mentioned really makes more sense. Anyway, I'm available to help with the translation. If you want to continue when the right time comes, it would be great to make such good content accessible to more people. I'll be following the repo progress and will soon take a look at the new additions. Thank you for sharing your knowledge.

**Pull request closed without merging**
